appId: com.shiflow.operationassistant
productName: 企微群发助手

directories:
  buildResources: assets
  output: dist

files:
  - out/**/*
  - assets/**/*
  - package.json

extraResources:
  - node_modules/robotjs/**/*
  - node_modules/node-window-manager/**/*

win:
  target:
    - target: nsis
      arch:
        - x64
  icon: assets/app_icon.ico

nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: 企微群发助手
  installerIcon: assets/app_icon.ico
  uninstallerIcon: assets/app_icon.ico

mac:
  target:
    - dmg
    - zip
  icon: assets/icon.icns